//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Xbox Inputs/InputPrimary.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPrimary: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPrimary()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPrimary"",
    ""maps"": [
        {
            ""name"": ""PlayerAct"",
            ""id"": ""be9518d7-c1d5-442a-bc38-3006f1ca1a8d"",
            ""actions"": [
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""f1438680-1f20-4920-b3bd-c8ba0d406241"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flashlight"",
                    ""type"": ""Button"",
                    ""id"": ""92a91eb8-d89b-49de-82ff-29686792c6a0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pickup"",
                    ""type"": ""Button"",
                    ""id"": ""9fb78981-e1fb-4ec7-9b62-f4a95d0209b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""2e6dbf2a-3ed3-4e92-97bc-7810e5703adc"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3b84ebd1-16d0-4a0c-b4f7-b129cf6fc5a0"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Selection"",
                    ""type"": ""PassThrough"",
                    ""id"": ""38907368-97d9-4401-8820-85a5a3e164ce"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Other Menu Selection"",
                    ""type"": ""PassThrough"",
                    ""id"": ""28db1640-e75c-4786-89a8-1385355ca7c5"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""1cec5133-cdb8-4558-9ad6-5db3870aa532"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""00f68099-f47f-4f9c-91f7-d85ff185aa96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c6b9e37f-75c4-4095-b500-502176cecf75"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""178af924-2ae6-4047-afdb-992089b36fa0"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb390259-0eca-43d0-952f-c635c35894eb"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Pickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""156fbfe7-60d6-4b54-9f1c-30a49bc646cf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b48caf4-2e1d-4891-ab4f-f349b2135878"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""50e634bd-b75f-4efa-af48-33fce379fab2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Selection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""502a37bf-e161-4b85-952c-458625ab7939"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""42544b6e-616f-43a1-8b8f-7483adbbc878"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a7e7c2a6-b7fd-4b7e-9de0-ed8f98d79c1d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a751819b-c59d-48c3-8812-18234b147000"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2ea76908-b439-4951-8ae9-074f6712f53a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Other Menu Selection"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fae4f971-0f0c-42c9-b3bb-00f318b8d4ba"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Other Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""809d56fc-aa6b-4129-a62b-298076b5b83a"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Other Menu Selection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f06589d8-c533-49a5-a6a4-77de01468ebd"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1326e7ea-1d45-439f-80b1-861c65dbd130"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Xbox Control Scheme"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox Control Scheme"",
            ""bindingGroup"": ""Xbox Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerAct
        m_PlayerAct = asset.FindActionMap("PlayerAct", throwIfNotFound: true);
        m_PlayerAct_Crouch = m_PlayerAct.FindAction("Crouch", throwIfNotFound: true);
        m_PlayerAct_Flashlight = m_PlayerAct.FindAction("Flashlight", throwIfNotFound: true);
        m_PlayerAct_Pickup = m_PlayerAct.FindAction("Pickup", throwIfNotFound: true);
        m_PlayerAct_Move = m_PlayerAct.FindAction("Move", throwIfNotFound: true);
        m_PlayerAct_Camera = m_PlayerAct.FindAction("Camera", throwIfNotFound: true);
        m_PlayerAct_MenuSelection = m_PlayerAct.FindAction("Menu Selection", throwIfNotFound: true);
        m_PlayerAct_OtherMenuSelection = m_PlayerAct.FindAction("Other Menu Selection", throwIfNotFound: true);
        m_PlayerAct_Pause = m_PlayerAct.FindAction("Pause", throwIfNotFound: true);
        m_PlayerAct_Sprint = m_PlayerAct.FindAction("Sprint", throwIfNotFound: true);
    }

    ~@InputPrimary()
    {
        UnityEngine.Debug.Assert(!m_PlayerAct.enabled, "This will cause a leak and performance issues, InputPrimary.PlayerAct.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerAct
    private readonly InputActionMap m_PlayerAct;
    private List<IPlayerActActions> m_PlayerActActionsCallbackInterfaces = new List<IPlayerActActions>();
    private readonly InputAction m_PlayerAct_Crouch;
    private readonly InputAction m_PlayerAct_Flashlight;
    private readonly InputAction m_PlayerAct_Pickup;
    private readonly InputAction m_PlayerAct_Move;
    private readonly InputAction m_PlayerAct_Camera;
    private readonly InputAction m_PlayerAct_MenuSelection;
    private readonly InputAction m_PlayerAct_OtherMenuSelection;
    private readonly InputAction m_PlayerAct_Pause;
    private readonly InputAction m_PlayerAct_Sprint;
    public struct PlayerActActions
    {
        private @InputPrimary m_Wrapper;
        public PlayerActActions(@InputPrimary wrapper) { m_Wrapper = wrapper; }
        public InputAction @Crouch => m_Wrapper.m_PlayerAct_Crouch;
        public InputAction @Flashlight => m_Wrapper.m_PlayerAct_Flashlight;
        public InputAction @Pickup => m_Wrapper.m_PlayerAct_Pickup;
        public InputAction @Move => m_Wrapper.m_PlayerAct_Move;
        public InputAction @Camera => m_Wrapper.m_PlayerAct_Camera;
        public InputAction @MenuSelection => m_Wrapper.m_PlayerAct_MenuSelection;
        public InputAction @OtherMenuSelection => m_Wrapper.m_PlayerAct_OtherMenuSelection;
        public InputAction @Pause => m_Wrapper.m_PlayerAct_Pause;
        public InputAction @Sprint => m_Wrapper.m_PlayerAct_Sprint;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAct; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActActionsCallbackInterfaces.Add(instance);
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Flashlight.started += instance.OnFlashlight;
            @Flashlight.performed += instance.OnFlashlight;
            @Flashlight.canceled += instance.OnFlashlight;
            @Pickup.started += instance.OnPickup;
            @Pickup.performed += instance.OnPickup;
            @Pickup.canceled += instance.OnPickup;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @MenuSelection.started += instance.OnMenuSelection;
            @MenuSelection.performed += instance.OnMenuSelection;
            @MenuSelection.canceled += instance.OnMenuSelection;
            @OtherMenuSelection.started += instance.OnOtherMenuSelection;
            @OtherMenuSelection.performed += instance.OnOtherMenuSelection;
            @OtherMenuSelection.canceled += instance.OnOtherMenuSelection;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
        }

        private void UnregisterCallbacks(IPlayerActActions instance)
        {
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Flashlight.started -= instance.OnFlashlight;
            @Flashlight.performed -= instance.OnFlashlight;
            @Flashlight.canceled -= instance.OnFlashlight;
            @Pickup.started -= instance.OnPickup;
            @Pickup.performed -= instance.OnPickup;
            @Pickup.canceled -= instance.OnPickup;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @MenuSelection.started -= instance.OnMenuSelection;
            @MenuSelection.performed -= instance.OnMenuSelection;
            @MenuSelection.canceled -= instance.OnMenuSelection;
            @OtherMenuSelection.started -= instance.OnOtherMenuSelection;
            @OtherMenuSelection.performed -= instance.OnOtherMenuSelection;
            @OtherMenuSelection.canceled -= instance.OnOtherMenuSelection;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
        }

        public void RemoveCallbacks(IPlayerActActions instance)
        {
            if (m_Wrapper.m_PlayerActActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActActions @PlayerAct => new PlayerActActions(this);
    private int m_XboxControlSchemeSchemeIndex = -1;
    public InputControlScheme XboxControlSchemeScheme
    {
        get
        {
            if (m_XboxControlSchemeSchemeIndex == -1) m_XboxControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Xbox Control Scheme");
            return asset.controlSchemes[m_XboxControlSchemeSchemeIndex];
        }
    }
    public interface IPlayerActActions
    {
        void OnCrouch(InputAction.CallbackContext context);
        void OnFlashlight(InputAction.CallbackContext context);
        void OnPickup(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnMenuSelection(InputAction.CallbackContext context);
        void OnOtherMenuSelection(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
    }
}
